/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package semi.project.com.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import semi.project.com.Main.MainDAO;
import semi.project.com.Main.MainDTO;
import semi.project.com.product.ProductDAO;
import semi.project.com.product.ProductDTO;

/**
 *
 * @author dbstj
 */
public class AdminPd extends javax.swing.JFrame implements ActionListener{
    private ProductDAO productDao;
    private MainDAO mainDao;
    private DefaultTableModel model = new DefaultTableModel();
    private String[] colNames = {"상품 넘버", "상품 이름", "상품 가격"};


    /**
     * Creates new form AdminPd
     */
    public AdminPd() {
        mainDao = new MainDAO();
        initComponents();
    
        init();
        addEvent();
        showAllPd();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfPrice = new javax.swing.JTextField();
        tfName = new javax.swing.JTextField();
        tfQty = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        taDesc = new javax.swing.JTextArea();
        btDel = new javax.swing.JButton();
        btEdit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tfNo = new javax.swing.JTextField();
        btAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "상품 넘버", "상품 이름", "상품 가격"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table2);
        if (table2.getColumnModel().getColumnCount() > 0) {
            table2.getColumnModel().getColumn(0).setResizable(false);
            table2.getColumnModel().getColumn(0).setPreferredWidth(40);
            table2.getColumnModel().getColumn(1).setResizable(false);
            table2.getColumnModel().getColumn(1).setPreferredWidth(100);
            table2.getColumnModel().getColumn(2).setResizable(false);
            table2.getColumnModel().getColumn(2).setPreferredWidth(50);
        }

        jLabel1.setText("상품 이름:");

        jLabel2.setText("상품 가격:");

        jLabel3.setText("상품 설명:");

        jLabel4.setText("상품 수량:");

        taDesc.setColumns(20);
        taDesc.setRows(5);
        jScrollPane2.setViewportView(taDesc);

        btDel.setText("상품 삭제");
        btDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDelActionPerformed(evt);
            }
        });

        btEdit.setText("상품 수정");

        jLabel5.setText("상품 넘버:");

        btAdd.setText("상품 추가");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAdd)
                        .addGap(61, 61, 61)
                        .addComponent(btDel)
                        .addGap(50, 50, 50)
                        .addComponent(btEdit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfQty, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btDel)
                            .addComponent(btEdit)
                            .addComponent(btAdd))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btDelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btDel;
    private javax.swing.JButton btEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea taDesc;
    private javax.swing.JTable table2;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfNo;
    private javax.swing.JTextField tfPrice;
    private javax.swing.JTextField tfQty;
    // End of variables declaration//GEN-END:variables

    private void init() {
      setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
    }

    private void addEvent() {
        table2.addMouseListener(new EventHandler());
        btEdit.addActionListener(this);
        btDel.addActionListener(this);
        btAdd.addActionListener(this);
    }

    private void showAllPd() {
        DecimalFormat df = new DecimalFormat("#,###");
        try {
            ArrayList<ProductDTO> list = mainDao.selectPD();
            
            String[][] data = new String[list.size()][3];
            
            for(int i =0; i<list.size(); i++){
                ProductDTO dto = list.get(i);
                String no = dto.getPdNo()+"";
                data[i][0] = no;
                data[i][1] = dto.getPdName();
                String price = df.format(dto.getPdPrice());
                data[i][2] = price;
            }
            model.setDataVector(data, colNames);
            table2.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(AdminPd.class.getName()).log(Level.SEVERE, null, ex);
        }
          
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==btEdit){
            try {
                pdEdit();
            } catch (SQLException ex) {
                Logger.getLogger(AdminPd.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if(e.getSource()==btDel){
            try {
                pdDel();
            } catch (SQLException ex) {
                Logger.getLogger(AdminPd.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (e.getSource()==btAdd){
            try {
                pdInsert();
            } catch (SQLException ex) {
                Logger.getLogger(AdminPd.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void pdEdit() throws SQLException {
        String no = tfNo.getText();
        String name = tfName.getText();
        int price = Integer.parseInt(tfPrice.getText());
        String desc = taDesc.getText();
        int qty = Integer.parseInt(tfQty.getText());

        
        if(no.isEmpty() || no==null){
            JOptionPane.showMessageDialog(this, "수정할 상품을 선택해주세요.");
        } 
        if(name.isEmpty() || name==null) {
            JOptionPane.showMessageDialog(this, "상품명은 공백으로 둘 수 없습니다.");
        }
        if(price<0) {
            JOptionPane.showMessageDialog(this, "금액은 양수로 입력해주세요.");
        }
        
        int no2 = Integer.parseInt(tfNo.getText());
        String img = mainDao.PdselectByNo(no2).getPdImg();
        ProductDTO dto = new ProductDTO();
        dto.setPdNo(no2);
        dto.setPdName(name);
        dto.setPdPrice(price);
        dto.setPdQty(qty);
        dto.setPdImg(img);
        dto.setPdDesc(desc);
        
        
        int cnt = mainDao.updatePd(dto);
        
        if(cnt>0){
            JOptionPane.showMessageDialog(this, "상품 수정 완료");
            showAllPd();
        } else {
            JOptionPane.showMessageDialog(this, "상품 수정 실패");
        }
    }

    private void pdDel() throws SQLException {
        String no = tfNo.getText();
        if(no==null || no.isEmpty()){
            JOptionPane.showMessageDialog(this, "상품을 선택해주세요.");
            return;
        }
        ProductDTO dto = new ProductDTO();
        
        String pdname = tfName.getText();
        int pdprice = Integer.parseInt(tfPrice.getText());
        int pdqty = 0;
        String pddesc = taDesc.getText();
        String pdimg = "테스트";
        
        dto.setPdName(pdname);
        dto.setPdNo(Integer.parseInt(no));
        dto.setPdPrice(pdprice);
        dto.setPdQty(pdqty);
        dto.setPdDesc(pddesc);
        dto.setPdImg(pdimg);
        
        
        int result = JOptionPane.showConfirmDialog(this, "삭제하시겠습니까", "삭제", JOptionPane.YES_NO_OPTION);
         if(result==JOptionPane.YES_OPTION){
             int cnt = mainDao.updatePd(dto);
             
             if(cnt>0){
                 JOptionPane.showMessageDialog(this, "상품 삭제 완료");
                 showAllPd();
             } else{
                 JOptionPane.showMessageDialog(this, "상품 삭제 실패");
             }
         }
        
        
    }

    private void pdInsert() throws SQLException {
        String pdName = tfName.getText();
        int pdPrice = Integer.parseInt(tfPrice.getText());
        int pdQty = Integer.parseInt(tfQty.getText());
        String desc = taDesc.getText();
        
        ProductDTO dto = new ProductDTO();
        dto.setPdName(pdName);
        dto.setPdPrice(pdPrice);
        dto.setPdQty(pdQty);
        dto.setPdDesc(desc);
        
        int cnt = mainDao.addPd(dto);
        
        if(cnt>0){
            JOptionPane.showMessageDialog(this, "상품 등록되었습니다.");
            showAllPd();
        }else{
            JOptionPane.showMessageDialog(this, "상품 등록 실패!");
        }
    }

    class EventHandler extends MouseAdapter implements ItemListener{

        @Override
        public void mouseClicked(MouseEvent e) {
            int row = table2.getSelectedRow();
            String no = (String) table2.getValueAt(row, 0);
            
            
            try {
                ProductDTO dto = mainDao.PdselectByNo(Integer.parseInt(no));
                tfName.setText(dto.getPdName());
                tfPrice.setText(dto.getPdPrice()+"");
                tfQty.setText(dto.getPdQty()+"");
                taDesc.setText(dto.getPdDesc());
                tfNo.setText(no);
                        
            } catch (SQLException ex) {
                Logger.getLogger(AdminPd.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
        @Override
        public void itemStateChanged(ItemEvent e) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

       
    }
}
